dummy_image:
    annotation: apps/plm/dummy_datasets/image/annotations.jsonl
    root_dir: apps/plm/dummy_datasets/image/images

dummy_multi_image:
    annotation: apps/plm/dummy_datasets/multi_image/annotations.jsonl
    root_dir: apps/plm/dummy_datasets/multi_image/images

dummy_image_region:
    annotation: apps/plm/dummy_datasets/image_region/annotations.jsonl
    root_dir: apps/plm/dummy_datasets/image_region/images

dummy_video:
    annotation: apps/plm/dummy_datasets/video/annotations.jsonl
    root_dir: apps/plm/dummy_datasets/video/videos

dummy_text:
    annotation: apps/plm/dummy_datasets/text/annotations.jsonl

dummy_stc_RDCap:
    annotation: apps/plm/dummy_datasets/plm_stc/RDCap.jsonl
    root_dir: apps/plm/dummy_datasets/plm_stc/videos

dummy_stc_RCap:
    annotation: apps/plm/dummy_datasets/plm_stc/RCap.jsonl
    root_dir: apps/plm/dummy_datasets/plm_stc/videos

dummy_stc_RTLoc:
    annotation: apps/plm/dummy_datasets/plm_stc/RTLoc.jsonl
    root_dir: apps/plm/dummy_datasets/plm_stc/videos

sa1b:
    annotation: /checkpoint/yashs/datasets/PLM_Image_Auto/sa1b/train.jsonl
    root_dir: /checkpoint/yashs/datasets/PLM_Image_Auto/sa1b/images

LLaVA-Pretrain:
    annotation: /checkpoint/yashs/datasets/LLaVA-Pretrain/train.jsonl
    root_dir: /checkpoint/yashs/datasets/LLaVA-Pretrain/images

LLaVA-Instruct-150k:
    annotation: /checkpoint/yashs/datasets/LLaVA-Instruct-150K/train.jsonl
    root_dir: /datasets01/COCO/022719/train2017

Cambrian-Stage1:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-Alignment/train.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-Alignment/

Cambrian-Shuffled-Stage1:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-Alignment/train_shuffled.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-Alignment/

Cambrian10M-Shuffled:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/Cambrian10M_shuffled.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/Cambrian7M_shuffled.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Code:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/code.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Counting:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/counting.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_General:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/general.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Language:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/language.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Math:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/math.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Ocr:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/ocr.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/

Cambrian7M-Shuffled_Science:
    annotation: /fsx-checkpoints/yashs/datasets/Cambrian-10M/jsons/7M_by_category/science.jsonl
    root_dir: /fsx-checkpoints/yashs/datasets/Cambrian-10M/